- src/components/TransactionSender.vue
- src/lib/RpcApi.ts
- src/router.ts
- src/views/Checkout.vue
- src/views/CheckoutOverview.vue
- src/views/CheckoutSelectAccount.vue
- src/views/SignTransaction.vue
- src/views/SignTransactionSuccess.vue
To enable correct routing when returning from Keyguard and to move transaction creation and sending logic into a shared `TransactionSender` component. This component currently only assembles the transaction and replies it to the RPC client, but will in the future be responsible for relaying the transaction to a server or creating the network consensus to send directly.
> Refactor SignTransaction and Checkout success screens

- client/AccountsClient.ts
- client/package.json
- client/rollup.config.js
- demos/Demo.ts
Since "Accounts Manager" is an invented name, and the repo and subdomain is only called `accounts`, why not stay with that and name the client for it the `AccountsClient`.
This PR renames the classes and build files to be `AccountsClient.es.js` etc...
> Rename AccountsManagerClient => AccountsClient

- package.json
- public/index.html
- src/App.vue
- src/components/CheckoutDetails.vue
- src/components/Network.vue
- src/components/Success.vue
- src/views/AddAccountSuccess.vue
- src/views/Checkout.vue
- src/views/CheckoutOverview.vue
- src/views/CheckoutTransmission.vue
- src/views/LoginSuccess.vue
- src/views/SignTransactionSuccess.vue
- src/views/SignupSuccess.vue
- src/views/SignupTypeSelector.vue
- src/views/SimpleSuccess.vue
- yarn.lock
Resolves #48.
Use @nimiq/nimiq-style in Accounts Manager.
Also includes additions of `buttonText` and `disabled` props to the `Success.vue` component to enable `SignTransactionSuccess.vue` to use it.
Screenshots:
> Adapt design to styleguide

- src/lib/RpcApi.ts
- src/main.ts
- src/views/ActiveAccountSelector.vue
- src/views/AddAccount.vue
- src/views/AddAccountSuccess.vue
- src/views/ChangePassphrase.vue
- src/views/Checkout.vue
- src/views/CheckoutOverview.vue
- src/views/CheckoutTransmission.vue
- src/views/ErrorHandler.vue
- src/views/Export.vue
- src/views/ExportFile.vue
- src/views/ExportWords.vue
- src/views/Login.vue
- src/views/LoginSuccess.vue
- src/views/Logout.vue
- src/views/LogoutSuccess.vue
- src/views/Rename.vue
- src/views/SignMessage.vue
- src/views/SignMessageOverview.vue
- src/views/SignMessageSuccess.vue
- src/views/SignTransaction.vue
- src/views/SignTransactionSuccess.vue
- src/views/SignupSuccess.vue
- src/views/SignupTypeSelector.vue
- src/views/SimpleSuccess.vue
To enable both secondary requests (e.g. importing an account during checkout) and iOS cookie writing, we centralize the replying to the caller into the `RpcApi` class and package all `@nimiq/rpc` dependencies there.
This removes a lot of dependencies from all views.
> Use centralized Vue.$rpc methods

- src/router.ts
- src/views/SignupErrorHandler.vue
It only handles the back button in the Keyguard, but now it adheres to the error handling convention.
The CheckoutErrorHandler is moved out from Checkout's children, to not render the payment-info-line and the page while processing an error.
> Use SignupErrorHandler

- client/AccountsClient.ts
- src/router.ts
- tslint.json
Also disable export-file & export-words routes.
> Split code per route for more performant deployment

- src/lib/RequestTypes.ts
- src/router.ts
- src/views/LoginErrorHandler.vue
- src/views/SignupSuccess.vue
- src/views/SignupTypeSelector.vue
Allows the user to click the 'Already have a wallet?' and 'Don't have a wallet yet?' buttons in Create (Accounts) and Import (Keyguard).
Needs https://github.com/nimiq/keyguard-next/pull/126
> Switch from import to create and vice-versa

- package.json
- src/components/Network.vue
- yarn.lock
- use same static NetworkClient singleton instance across all Network components to avoid the need to establish consensus multiple times
- when Network component gets destroyed, free up event listeners to avoid memory leak
- define event names as enum
> Network improvements

- public/blocking.css
- public/index.html
Copied styles from `https://fonts.googleapis.com/css?family=Muli:400,600,700` and `https://fonts.googleapis.com/css?family=Fira+Mono&text=0123456789ABCDEFGHJKLMNPQRSTUVXY` but commented Vietnamese out.
Also manually added `woff` fallback :dog:
> Integrate fonts css into blocking.css

- client/AccountsClient.ts
- client/RequestBehavior.ts
- client/package.json
- client/yarn.lock
- package.json
- src/App.vue
- src/components/CheckoutDetails.vue
- src/components/Network.vue
- src/lib/RpcApi.ts
- src/main.ts
- src/store.ts
- src/views/CheckoutErrorHandler.vue
- src/views/CheckoutOverview.vue
- src/views/LoginErrorHandler.vue
- src/views/SignMessage.vue
- src/views/SignMessageErrorHandler.vue
- src/views/SignMessageOverview.vue
- src/views/SignTransaction.vue
- src/views/SignupErrorHandler.vue
- yarn.lock
With these changes, and the according changes in the @nimiq/rpc and @nimiq/keyguard-client libs (already included here as package dependencies), it becomes possible for the user to refresh the page at every step throughout a request flow, without loosing the request or getting stuck.
> Enable page refresh at every step

- src/lib/CookieJar.ts
- src/lib/WalletInfo.ts
- src/views/LoginSuccess.vue
- src/views/Rename.vue
- tests/unit/CookieJar.spec.ts
https://github.com/nimiq/keyguard-next/pull/155 changed the type number for LEGACY and BIP39 types. This PR adapts them in the Accounts Manager.
> Adapt WalletType enum to new type standard

- package.json
- src/lib/RpcApi.ts
- src/views/AddAccount.vue
- src/views/ChangePassword.vue
- src/views/Export.vue
- src/views/Login.vue
- src/views/Logout.vue
- src/views/SignMessage.vue
- src/views/SignTransaction.vue
- src/views/Signup.vue
- yarn.lock
By telling the KeyguardClient to return to the root and not to a path, the VuexRouter is not invoked and the path's component is not loaded, resulting in no `created()` or `mounted()` handlers firing and redirecting back to the Keyguard.
Requires https://github.com/nimiq/keyguard-next/pull/242.
> Use custom KeyguardClient returnURL to remove need for result guards

- src/views/ChangePassword.vue
- src/views/Export.vue
- src/views/Logout.vue
- src/views/Rename.vue
- src/views/SignTransaction.vue
There was an error thrown through Sentry:
```
TypeError in done(src/views/Rename):
null is not an object (evaluating 'this.wallet.id')
./src/views/Rename.vue in done at line 126:29
```
This leads me to believe, that the request was not rejected when `mounted()` function found that the account ID does not exist.
Thus I now made it so that the requests are actually rejected when the account ID is not found.
> Reject request when account not found

- package.json
- src/components/LedgerUi.vue
- src/components/Loader.vue
- src/lib/LedgerApi.ts
- yarn.lock
Make the LedgerApi reject calls in Chrome 72+ and show a warning message as Chrome 72+ is currently incompatible with the ledger lib, see https://github.com/LedgerHQ/ledgerjs/issues/306.
The detection is done by user agent sniffing, as feature detection is probably not straight forward possible (Chrome 72+ fails only after some time with an unspecific timeout).
This requires https://github.com/nimiq/nimiq-utils/pull/21 to be merged first.
> Chrome Ledger support warning

- package.json
- src/lib/Constants.ts
- src/lib/CookieDecoder.ts
- src/lib/LabelingMachine.ts
- src/lib/WalletInfoCollector.ts
- src/views/AddAccountSuccess.vue
- src/views/SignupLedger.vue
- src/views/SignupSuccess.vue
- tests/unit/CookieJar.spec.ts
- yarn.lock
Uses the new `iqons-name` lib to generate automatic labels for addresses.
Also generates color-named labels for Keyguard accounts.
Only problem is, that the cookie does not encode the user-friendly address, and the iframe also does not have the Nimiq lib available, so there is no way to generate the default label, in case no label is stored in the cookie. It was originally planned to omit the label in the cookie, when it is the default label, to save cookie space, but this is currently not implemented anyways during cookie-writing. So the question is, should we remove the check for a label being omitted in the cookie?
> Use Iqons names for address labels

- public/ServiceWorker.js
- src/App.vue
Adds a service worker which intercepts all network requests to the same host as its own and prevents cookie data from being transmitted.
> Add cookie monster service worker

- jest.config.js
- package.json
- src/lib/CookieDecoder.ts
- src/lib/CookieJar.ts
- tests/unit/CookieJar.spec.ts
- yarn.lock
Testing of the removal and re-setting of the default labels is done via the byte-check of the encoded cookie (the labels are empty in the cookie bytes).
> Omit default labels in cookie

- src/lib/WalletInfoCollector.ts
This prevents having to wait for balance when the only possible account is already known. The balance is currently not used anywhere in Accounts, is also checked separately from the Safe and is checked again in Accounts before Checkout.
Resolves #175.
> Skip getting balance for imported legacy account

- package.json
- src/components/LedgerUi.vue
- src/components/Loader.vue
- src/components/WalletIdentifier.vue
- src/lib/LedgerApi.ts
- src/lib/RpcApi.ts
- src/router.ts
- src/views/AddAddressLedger.vue
- src/views/Checkout.vue
- src/views/CheckoutTransmission.vue
- src/views/ChooseAddress.vue
- src/views/LoginSuccess.vue
- src/views/LogoutSuccess.vue
- src/views/OnboardingSelector.vue
- src/views/Rename.vue
- src/views/SignMessage.vue
- src/views/SignMessageSuccess.vue
- src/views/SignupLedger.vue
- src/views/SignupSuccess.vue
- src/views/SimpleSuccess.vue
- yarn.lock
Initilly I tried to refactor `SignupLedger` such that `AddAddresLedger` and `AddAddressLedger` would inherit from a common abstract base class. But in the end it turned out more beautiful to separate bothm implementations.
Note that I still want to improve the visual style of this flow (e.g. state transitions, loading spinner) but will do this together with style changes to `SignupLedger`
> Add add-address flow for ledger

- src/components/Network.vue
- src/lib/LedgerApi.ts
- src/lib/RpcApi.ts
- src/lib/StaticStore.ts
- src/views/Checkout.vue
- src/views/CheckoutTransmission.vue
- src/views/SignMessage.vue
- src/views/SignMessageSuccess.vue
- src/views/SignTransaction.vue
- src/views/SignTransactionSuccess.vue
Small cleanup and fix for reload behavior:
- Don't transform `Uint8Array`s in stored `staticStore.keyguardRequest` as the `RpcApi` is able to handle them directly.
- Don't jump back to request's initial view on reload when navigated to a subsequent view. Relevant when user navigates from checkout to onboarding and reloads, from checkout to SignTransactionLedger and reloads or from onboarding to SignupLedger and reloads.
> Small window reload fixes

- README.md
We're already looking up element by ID and not using a query selector, so no "#" is needed in the parameter.
> Removed "#" from parameter in getElementById

- vue.config.js
Following the instructions from https://www.mistergoodcat.com/post/the-joy-that-is-source-maps-with-vuejs-and-typescript.
The breakpoint-able `.ts` and `.vue` files are now available in the devtools' sources under the `.` folder.
Resolves #127.
> Generate proper sourcemaps for .ts files

- demos/Demo.ts
- package.json
- src/components/Network.vue
- src/lib/AccountInfo.ts
- src/lib/AddressUtils.ts
- src/lib/Constants.ts
- src/lib/ContractInfo.ts
- src/lib/CookieDecoder.ts
- src/lib/CookieJar.ts
- src/lib/PublicRequestTypes.ts
- src/lib/WalletInfo.ts
- src/lib/WalletInfoCollector.ts
- src/store.ts
- src/views/Checkout.vue
- src/views/CheckoutTransmission.vue
- src/views/ChooseAddress.vue
- src/views/LoginSuccess.vue
- src/views/Migrate.vue
- src/views/Rename.vue
- src/views/SignTransaction.vue
- src/views/SignTransactionSuccess.vue
- src/views/SignupLedger.vue
- src/views/SignupSuccess.vue
- tests/unit/CookieJar.spec.ts
- tests/unit/WalletStore.spec.ts
- yarn.lock
Resolves #124.
For testing, you can import this legacy account that owns a genesis vesting contract in the testnet:
```
[
"engine",  "curtain",  "fringe",
"bean",    "hole",     "foot", 
"garage",  "bean",     "find",
"suit",    "ozone",    "kitchen",
"country", "stool",    "talent", 
"smoke",   "double",   "similar", 
"hazard",  "discover", "gauge", 
"gasp",    "settle",   "fabric"
]
```
or use latest Keyguard `master` branch and use the _Setup Legacy Accounts_ and _Migrate Legacy Accounts_ options in the Accounts Demos to import this account through migration.
> Add support for contracts

- README.md
- src/lib/PublicRequestTypes.ts
- src/lib/RequestParser.ts
- src/lib/RequestTypes.ts
- src/views/Checkout.vue
- src/views/SignTransaction.vue
Resolves #190.
- Enforce minimum set of required request properties
- Set defaults for optional properties to clean up setting fallbacks throughout the code
- Allow `extraData` for checkout and signTransaction to be a string
This actually fixes a bug in vue-components/PaymentInfoLine, where it displayed 'NaN NIM' when `fee` was omitted in the checkout request.
> Request parsing: required and default properties, extraData as string

- demos/Demo.ts
- public/iframe.html
- src/iframe.ts
- src/lib/AccountInfo.ts
- src/lib/ContractInfo.ts
- src/lib/CookieDecoder.ts
- src/lib/PublicRequestTypes.ts
- src/lib/WalletInfo.ts
- src/views/Migrate.vue
Instead of `WalletInfoEntry`, output the public `Account` type (as array) for `list()` and `migrate()` methods (latter of which results is currently not used in Safe, as migration is done via redirect and the new list of accounts is loaded with list() on return page load).
This is required, as the `WalletInfoEntry` does not contain contracts' user-friendly address anywhere, only addresses in serialized form (the addresses are a map with the user-friendly address as key, but the contracts are not). Because we have no serialized-to-user-friendly-address methods in the Safe (no Nimiq lib, and I also don't want to add a helper for this), we need another result type for contracts.
It was thus fitting to change the whole result to the public result type also returned by `signup()` and `login()` …
> Use Account[] for list and migration results

- src/views/SignMessage.vue
Add a filter to remove contracts from `processedWallets`.
Also fix wording from 'account' to 'address'.
> Hide contracts in signMessage

- README.md
SSH URLs only work for those with push access to this repo, HTTPS urls work for everyone.
> Make clone URL work for those without push access

- src/lib/RpcApi.ts
- src/views/AddAccount.vue
- src/views/AddAccountSuccess.vue
- src/views/AddAddressLedger.vue
- src/views/ChangePassword.vue
- src/views/Export.vue
- src/views/ExportSuccess.vue
- src/views/Logout.vue
- src/views/Rename.vue
Waiting for https://github.com/nimiq/accounts/pull/183 to be merged first.
- Check for existence of account required for a request in `RpcApi` already without the need to load the request view.
- Allow logout from account in Keyguard even if it was deleted (e.g by the browser) in the accounts manager database
> Check for invalid account in rpc api already and allow logout of deleted accounts

- README.md
- client/AccountsClient.ts
- demos/Demo.ts
- package.json
- src/lib/PublicRequestTypes.ts
- src/views/SignMessage.vue
- src/views/SignMessageSuccess.vue
- tests/unit/AccountsClient.spec.ts
- yarn.lock
- Forward message as-is to Keyguard
- Do not return signed data from signMessage
- Export message prefix in client
- Update docs for reworked signature validation
To use with https://github.com/nimiq/keyguard-next/pull/256.
> Rework message signing

- package.json
- src/components/Loader.vue
- src/iframe.ts
- src/lib/WalletInfoCollector.ts
- src/store.ts
- src/views/ErrorHandler.vue
- src/views/Login.vue
- src/views/OnboardingSelector.vue
- yarn.lock
Accounts marked with `keyMissing = true` will be able to be also managed in the revamped management screen (#170). Until then, they will simply be hidden from apps.
Resolves #121.
> KEY_NOT_FOUND error page and hiding keyMissing accounts

- README.md
- demos/Demo.ts
- demos/index.html
- src/lib/PublicRequestTypes.ts
- src/lib/RequestParser.ts
- src/lib/RequestTypes.ts
- src/store.ts
- src/views/Checkout.vue
- src/views/SignMessage.vue
- src/views/SignTransaction.vue
When the `sender` address exists and has enough balance, the user is directly forwarded to the Keyguard for signing.
When the address does either not exist or does not have sufficient balance, the user is either displayed the address selector list (default), or - in case `forceSender = true` - the request is rejected with an exception.
Resolves #212.
> Allow passing a sender to checkout

- README.md
A change is also needed at https://www.npmjs.com/package/@nimiq/accounts-client as both the npm and github readmes have the last versions link rather than the current one.
> Update version from 0.2 to 0.3 in CDN install URLs

- README.md
- demos/index.html
- jest.config.js
- package.json
- src/config/config.local.ts
- src/config/config.mainnet.ts
- src/config/config.testnet.ts
- src/lib/RpcApi.ts
- src/main.ts
- tsconfig.json
- tsconfig.local.json
- tsconfig.mainnet.json
- tsconfig.testnet.json
- vue.config.js
- yarn.lock
Introduces a new config parameter `redirectTarget`, where the user is redirected if the rpc server doesn't receive a request. Needs https://github.com/nimiq/rpc/pull/17 to be merged and released first.
I also moved the config files from root to `src/config` to emphasise that they take effect at build-time and not at run-time and to be consistent with keyguard.
> Handle absence of request

- client/AccountsClient.ts
- src/iframe.ts
- src/lib/PublicRequestTypes.ts
- src/lib/WalletInfoCollector.ts
- src/views/LoginSuccess.vue
- src/views/SignupLedger.vue
This PR updates `LoginSuccess` and `WalletInfoCollector`. 
Single returned Accounts still get added as usual. 
For multiple returned Accounts, if there are some which have either a balance or a transaction history, only those will be added. Otherwise none of the Accounts was previously used and then only the newest AccountType (BIP39) will be added.
The accounts which did not got added, will also correctly be released in Keyguard.
needs nimiq/keyguard-next#297
resolves #147
> Enable automatic Account retrieval in case login returns multiple Accounts

- package.json
- public/index.html
- yarn.lock
make browser-warning.js and blocking.css paths absolute; update @nimiq/browser-warning, fix Nimiq version
> Fix paths for subrequest refreshs

- src/lib/WalletInfoCollector.ts
- src/views/LoginSuccess.vue
- src/views/SignupLedger.vue
- Split collection for legacy / Bip39 / ledger accounts into separate methods
- Join logic for vesting contract detection into a single method
- Make sure the network is initialized before requesting transaction histories
- Remove the checkLegacyActivity flag on _initializeDependencies
- Performance improvements:
- don't create keyguard client if not needed
- don't request balance / transaction history for initial accounts if not needed
Not always requesting the balance for the initial accounts implies that the
WalletInfoCollector now does not guarantee anymore to return fully updated balances.
> Wallet info collector refactor

- public/blocking.css
- src/App.vue
Add layout for mobile screens, where the page is sticking to the bottom of the screen and there are no margins left and right. The global close button is at the top right next to the Nimiq logo.
Same problems with `html, body` overflow and scrollbars as in https://github.com/nimiq/keyguard-next/pull/342.
> Mobile styles

- public/blocking.css
- src/App.vue
- src/main.ts
Following advice on https://stackoverflow.com/a/44887358/4204380 and the docs on https://router.vuejs.org/guide/advanced/navigation-guards.html#navigation-guards, this makes the loading spinner display while the router is (lazy-)loading a route.
This prevents the loading spinner from disappearing as soon as the request/result is known but before the route's component is shown (because the component loading is only started after the request/result is set) and thus presents a "gap in loading".
> Show loader while router loads route

- package.json
- public/blocking.css
- src/iframe.ts
- src/lib/AccountInfo.ts
- src/lib/RpcApi.ts
- src/views/ExportSuccess.vue
- src/views/Migrate.vue
- yarn.lock
Resolves #233.
When during AM startup it is detected, that no accounts are stored, but the Keyguard has legacy accounts, then the current request is stored as `originalRouteName` and the user is redirected to the migration screen. When returning from an Keyguard-Export request, the user is again redirected to migration.
Only when migration succeeds and accounts are stored in the AM, then everything is back to normal and the orignal request is triggered (if it was not `migrate()` in the first place).
> Trigger key migration screen when necessary

- src/main.ts
Relevant for example when the choose address flow forwards to the onboarding when no accounts are available.
> Fix router loading state for quick subsequent navigation

- src/lib/LedgerApi.ts
- src/lib/WalletInfoCollector.ts
- src/lib/WalletStore.ts
- src/views/Migrate.vue
- src/views/SignupSuccess.vue
- tests/unit/WalletStore.spec.ts
- tests/unit/_setup.ts
Hashing with a random salt that does not leave the hub to avoid that an
external app can derive wallet id's from public keys (Legacy and Ledger
accounts) or get a hint for private key guessing / brute forcing (for BIP39)
as hashing the private key is cheaper than deriving the public key.
> Wallet id salting

- src/lib/WalletInfoCollector.ts
- src/views/Checkout.vue
- src/views/CheckoutTransmission.vue
- src/views/LoginSuccess.vue
Resolves #280.
Adds network-event depending status updates to the Checkout loading screens and displays the number of detected accounts during Login.
> Add status updates to Checkout and Login

- client/HubApi.ts
- src/lib/PublicRequestTypes.ts
- src/lib/RequestParser.ts
- src/lib/RequestTypes.ts
- src/views/OnboardingSelector.vue
I am not sure if we should add the flag to the `BasicRequest`, as that would mean it would be available for every request, which it isn't. It's only respected in the onboarding menu.
> Preserve a disableBack flag through the parser.

- src/store.ts
- src/views/ErrorHandler.vue
The `ErrorHandler` still expected e.g. the `sign-transaction` request to contain the `walletId` in the request, which it doesn't do anymore (sign-transaction only uses the `sender` prop). So these changes now fix the handler to use the existing props.
It also now redirects to Keyguard login (import) even when Hub wallet data is not found. (This last part is optional and can be removed from this PR, if we don't want to do this (with these changes the ErrorHandler should again handle all KEY_NOT_FOUND errors correctly and hub-meta-data should always exist (if it doesn't, the RpcApi should reject the request already at the beginning)).
> Fix ErrorHandler for changed request types

- package.json
- src/components/Network.vue
- yarn.lock
Requires https://github.com/nimiq/network/pull/11 to be published first.
Fixes a bug introduced in https://github.com/nimiq/hub/pull/312 that results in calls to instances of the Network component to never execute for instances that are not the first created. This bug occurred as the promise waiting for the client initialization was not shared across Network component instances.
This fix has specifically an implication on Checkouts with Ledger where multiple views with a Network component are involved.
> Fix initialization of Network client

- src/lib/LedgerApi.ts
- src/lib/WalletInfoCollector.ts
- src/views/SignupLedger.vue
This avoids unnecessary calls to the Ledger and fixes Sentry error HUB-43 (Only one
call to Ledger at a time allowed) which occurred when the wallet info collection
errored (for example due to a failed network request) and SignupLedger immediately
retried to launch the wallet collection.
It's recommendable to ignore whitespace changes for easier reviewability.
> WalletInfoCollector,SignupLedger: cancel Ledger account derivation on error

- src/views/LoginSuccess.vue
- src/views/SignupLedger.vue
Warn user that addresses are potentially incomplete if transaction receipts could not be retrieved successfully.
This behavior is similar to the incomplete import of Keyguard accounts (https://github.com/nimiq/hub/pull/179).
However, the Ledger flow eventually ends in a success screen, even if there was a warning which I consider more consistent. (Edit: I just saw LoginSuccess had been changed to this behavior in a later commit too)
> Warn about potentially incomplete addresses on ledger signup

- src/store.ts
- src/views/Checkout.vue
- src/views/ChooseAddress.vue
- src/views/LoginSuccess.vue
- src/views/SignMessage.vue
- src/views/SignupLedger.vue
- src/views/SignupSuccess.vue
To avoid having to actively check for and add newly added accounts from a side-request, the side-requests should add their created/logged-in accounts to the Vuex store automatically. This reduces code and headaches.
> Add new accounts to Vuex when they are created, not when they are needed

- README.md
- src/config/config.local.ts
- src/config/config.mainnet.ts
- src/config/config.testnet.ts
- src/lib/RpcApi.ts
- src/views/RequestError.vue
This fixes the issue of a redirect happening in a popup, when the popup is initially blocked by a popup-blocker but then opened anyway from the browser prompt. In those cases, the reference to the popup is lost in the opening window and the popup receives no postMessage request within the timeout. Additionally, because the reference from the opening window got lost, the `window.opener` in the popup is now `null`, triggering the redirect case, opening the Safe in the popup.
I believe we don't need a redirect-on-error and can just display the error page. The error page then detects if the user can go back to the sending page, or close the window otherwise.
> Show error page instead of redirect in case of missing request

- package.json
- src/components/Network.vue
- src/views/Checkout.vue
- src/views/Migrate.vue
- yarn.lock
This PR adds support for the new nano-api with Client API to the `master` branch.
The changes required in the cashlink code will follow after this PR or the cashlink PR has been merged, whichever is first.
> Adapt to nano-api with Core Client (1/2)

- src/lib/RpcApi.ts
This PR changes the creation of the Hub and Keyguard API handler functions to only be created once and then re-used, instead of creating huge methods multiple times, once for each API method.
This should slightly reduce initialization time for the Hub and reduce memory usage.
The diff should be viewed with whitespace ignored, because the indentation of big blocks of code changed.
> Create API handler functions only once

- src/components/IdenticonSelector.vue
This PR fixes a 'Cannot read property 'focus' of undefined` Error in `IdenticonSelector`.
> IdenticonSelector: only focus on selection, not on dismissal.

- src/lib/CheckoutServerApi.ts
To support various e-commerce authentication systems, we should allow to send credentials (cookies and auth headers) with the webhook request. However, because including the credentials requires the server to answer with a specific header (as per CORS rules), this might fail if the server omits this header. We then simply try again with the credentials omitted.
> Send credentials with the webhook

- src/lib/PublicRequestTypes.ts
- src/lib/RequestParser.ts
- src/lib/RequestTypes.ts
- src/views/SignTransaction.vue
Forward recipient label to Keyguard to display there.
This was previously part of the `sebastian/cashlink-create-manage` branch.
> Allow external recipient label for sign-transaction requests

- public/blocking.css
- src/App.vue
This reduces the logo byte-size and properly aligns the global-close button with the logo on mobile.
This was previously part of the `sebastian/cashlink-create-manage` branch.
> Logo simplification and mobile close-button alignment

- client/RequestBehavior.ts
Adds an overlay when the Hub is opened in a popup. Clicking on this overlay refocuses the popup.
Tested on Chrome (Desktop and Android), Firefox (Desktop), Safari (Mac). More tests are welcome!
I added some helper functions and variables so that the code can be better minified for the standalone builds (DOM variables & methods can't be minified, so abstracting them is the way to go).
Paypal Overlay for reference (click the "Try the buttons" buttons): https://developer.paypal.com/docs/checkout/
> HubApi Popup Overlay

- src/lib/CheckoutServerApi.ts
To encode in `application/x-www-form-urlencoded` format instead of `multipart/form-data`. URL-encoded form data is easier to handle by servers and favored to use for plain-text payloads. Multipart data should only be used for binary files like images.
**I have already deployed this change to the Testnet Hub** and tested it with both the CheckoutService and the WooCommerce plugin and both work with this change without requiring any server-side changes.
When debugging why the webhook in the CheckoutService did not work, I found that [Google Cloud Functions are not natively able to handle `multipart/form-data`](https://cloud.google.com/functions/docs/writing/http#handling_content_types). Thus I wondered why the Hub is sending the webhook POST data as `multipart/form-data` instead of …
> Use URLSearchParams for callback request data

- src/components/Network.vue
- src/lib/Helpers.ts
- src/lib/RpcApi.ts
- src/views/CashlinkManage.vue
- src/views/SignTransactionLedger.vue
This PR enables resending transactions after reload of the page.
This has been a feature of `CashlinkManage` for Keyguard Cashlink transactions before but is now also supported for Ledger transactions (checkout and cashlink).
Additionally, `CashlinkManage` can now detect for Keyguard transactions whether they have already been sent or not, and does now not resend a transaction on reload anymore but forwards directly to the management screen.
> Unrelayed tx caching

- src/components/Network.vue
Fixes two issues:
- Transaction relayed event listeners previously were removed even when it was another tx that was relayed. This way, `sendToNetwork` was not able to resolve anymore for one of the transactions, when two are sent at the same time.
- Previously, `getBlockchainHeight` reported one if called, before the consensus was established.
> Small network fixes

- client/HubApi.ts
- client/package.json
- client/types/Nimiq.d.ts
- client/types/index.d.ts
- client/yarn.lock
- Specifying "types" in package.json
- Adding `@nimiq/core-web` as a depencecy such that core types are included
- Adding big-integer as a dependency to include types
- Expose `PopupRequestBehavior` and `CashlinkState` enum
- Exporting `PublicRequestTypes` for convenience
> Fix client type export

- defer.sh
- package.json
- public/cashlink.html
- public/index.html
- vue.config.js
- yarn.lock
This makes it possible to also add the defer attribut to the Nimiq lib script, because the plugin also works in dev mode (the `defer.sh` bash script did not).
> Add defer attributes to script by webpack plugin

- public/cashlink.html
- public/index.html
- vue.config.js
Automatically detect during build whether to use cdn.nimiq.com
or cdn.nimiq-testnet.com. This way, this doesn't need to be
manually configured / cherry-picked for mainnet builds anymore.
> Automatically configure cdn

- package.json
- public/cashlink.html
- public/index.html
- src/cashlink.ts
- src/main.ts
- tsconfig.json
- types/BrowserWarning.d.ts
- yarn.lock
Update to browser warning 1.0.0 which now provides a share button,
fixes issues with old browsers, updated the warning for Edge
browsers, adds types and is minified.
The share button is customized such that it shares the caller url
instead of the hub itself which wouldn't make sense as the hub
request would not be available anymore when opening in another
tab or browser. Cashlinks however are shared normally.
> Update and customize browser warnings

- vue.config.js
Greatly reduce bundle size by setting 'devtool' to 'source-map' instead
of 'eval-source-map' on production builds. This enables code minification
and extracts source maps into separate files. The javascript files are now
only ~14.3% of the previous size (~17.2% when comparing gzipped).
Resolves #306
> Reduce js build size by minification and extracting source maps

- src/lib/WalletInfo.ts
- src/views/CashlinkCreate.vue
- src/views/ChangePassword.vue
- src/views/Checkout.vue
- src/views/Export.vue
- src/views/Logout.vue
- src/views/SignTransaction.vue
For a description of the problem this solves, see issue #260.
Resolves #260.
> Do not forward legacy wallet labels to Keyguard

- src/lib/RpcApi.ts
- src/views/CashlinkCreate.vue
- src/views/ChooseAddress.vue
- src/views/SignMessage.vue
#293 prompted me to review the error messages, so I did, and I found a few occurances where the wrong error message was thrown (e.g. when a wallet was searched for an address, but the wallet was not found, this means the address does not exist in the first place).
> Fix error message to reflect what was not found

- demos/Demo.ts
- src/components/CheckoutManualPaymentDetails.vue
- src/components/CheckoutOption.vue
- src/components/CurrencyInfo.vue
- src/components/NimiqCheckoutOption.vue
- src/components/NonNimiqCheckoutOption.vue
- src/lib/PublicRequestTypes.ts
- src/lib/RequestParser.ts
- src/lib/RequestTypes.ts
- src/lib/paymentOptions/NimiqPaymentOptions.ts
- src/lib/paymentOptions/ParsedPaymentOptions.ts
- src/views/Checkout.vue
- src/views/SignTransactionLedger.vue
This PR moves the extraData from `MultiCurrencyCheckout.extraData` to `NimiqDirectPaymntOptions.protoclSpecific.extraData` as it is only ever used in that case.
Additionally `fee`, `feePerByte` and `extraData` can now be `undefined` in `NimiqSpecifics` as `ParsedPaymentOptions.update()` determines the need for updating a value based on wether it is `undefined` or not. The constructor of `ParsedPaymentOptions` got a new argument `enforceDefaultValues` to account for the change.
> Move extraData from MultiCurrencyCheckoutRequest.extraData to NimiqDirectPaymentOptions.protocolSpecific.extraData.

- src/components/NimiqCheckoutOption.vue
- src/lib/RpcApi.ts
- src/views/CashlinkCreate.vue
- src/views/ChooseAddress.vue
- src/views/ErrorHandler.vue
- src/views/ExportSuccess.vue
- src/views/OnboardingSelector.vue
- src/views/SignMessage.vue
- src/views/SignTransactionLedger.vue
This PR removes `RpcApi.routerPush()` and `RpcApi.routerReplace()`. They are replaced with navigation guards on the router. 
As a remark for future use, that does also mean, that future calls to `Vue.$router.push()` now take a path, i.e `Vue.$router.push('/sign-transaction')` as argument. If a named route is used `Vue.$router.push({name: 'sign-transaction'})` must be used. That is different from how `Vue.$rpc.routerPush()` worked before this PR.
I replaced all current occurrences.
resolves #371
> RpcApi: Replace routerPush and routerReplace with navigation guards

- src/components/BitcoinCheckoutCard.vue
- src/components/CheckoutCard.vue
- src/components/EthereumCheckoutCard.vue
- src/components/NimiqCheckoutCard.vue
- src/components/NonNimiqCheckoutCard.vue
- src/views/Checkout.vue
Renaming the components as I think having `*PaymentOptions` and `*CheckoutOptions` is too confusing.
> Rename *CheckoutOption to *CheckoutCard

- src/components/Network.vue
- src/components/NimiqCheckoutCard.vue
- src/lib/Cashlink.ts
- src/lib/RequestParser.ts
- src/lib/WalletInfoCollector.ts
- src/lib/paymentOptions/NimiqPaymentOptions.ts
- src/views/AddAddressLedger.vue
- src/views/CashlinkCreate.vue
- src/views/ChooseAddress.vue
- src/views/Rename.vue
- src/views/SignTransactionLedger.vue
- src/views/SignupLedger.vue
Resolves #365.
The method `Nimiq.Address.fromString()` tries to read the input as a userfriendly address first, then as HEX and then as Base64. Because the userfriendly format is tried first, there is barely any performance penalty to this.
> Use Address.fromString in all places

- demos/Demo.ts
- src/lib/CheckoutServerApi.ts
This PR proposes to add checkout dummy data similar to the snippet already in use by Matheo, Sebastian and me to actual code base in a safe way.
This removes the need to always apply the snippet as a patch or from a stash when needed and the extra care to not include it in commits or builds. Additionally, it makes testing / developing easier for third party devs, that would need to write their own snippet.
Might be sufficient to resolve https://github.com/nimiq/hub/issues/377.
> CheckoutServerApi: serve dummy data in development mode

- src/config/config.local.ts
- src/config/config.mainnet.ts
- src/config/config.testnet.ts
- src/lib/Helpers.ts
- src/lib/RequestParser.ts
- src/lib/RpcApi.ts
- src/views/Checkout.vue
- src/views/SignTransactionLedger.vue
Adds a configuration option `allowsCheckoutWithoutNim: (origin: string) => boolean` that returns if a given origin is allowed to create Checkout requests without a NimPaymentOption.
For development, this is configured as always `true` by default, for the testnet this allows the CPL staging website, and for the mainnet this allows Checkout requests from non-API CPLs.
The only two necessary changes are in `RequestParser` lines 122-126, and in `Checkout.vue`, as the NIM currency is now not necessarily present anymore.
> NIM-less Checkout

- package.json
- src/iframe.ts
- src/lib/PublicRequestTypes.ts
- src/lib/Uid.ts
- src/lib/WalletInfo.ts
- src/views/ActivateBitcoinSuccess.vue
- src/views/AddVestingContract.vue
- src/views/LoginSuccess.vue
- src/views/Migrate.vue
- src/views/Rename.vue
- src/views/SetupSwapSuccess.vue
- src/views/SignupLedger.vue
- src/views/SignupSuccess.vue
- yarn.lock
This PR adds a new field to the `Account` type returned to the Wallet: a `uid`. It is returned everywhere where an account is returned.
Iframes in iOS/Safari, which don't have the `keyId` stored in the cookie, return an empty string. The wallet falls back to tracking swap volume via transaction history when the UID is not available, but since it is returned for signups, logins, renames, exports, it will soon be available for those users also.
Generating the UID is a runtime SHA256 hash, which is super fast and not noticeable until ~100 accounts per browser.
> The UID is used for the purpose of tracking Fastspot swap limits per user. It is generated from two deterministic values. The keyId of an account and its first NIM address, wich are always the same.
>
> The `keyId` is never passed to …
> Generate UIDs for WalletInfos and return them to the Wallet

- client/HubApi.ts
- demos/Demo.ts
- demos/index.html
- src/lib/PublicRequestTypes.ts
- src/lib/RequestParser.ts
- src/lib/RequestTypes.ts
- src/views/AddAccountSelection.vue
- src/views/ChooseAddress.vue
- yarn.lock
Allow the `ChooseAddress` request to also request a BTC address for the account of which the NIM address was selected. It does not enforce selecting an account that supports BTC, so the `btcAddress` in the result can still be `undefined`. I have additionally updated the `AccountSelector` component in vue-components a bit to display a "BTC" label next to BTC-enabled account labels, if a BTC address is expected in the result.
Additionally, I have made all filtering `AccountSelector` props available as request options, to filter the list of selectable addresses (which makes sense in the CPL case, where contract addresses should not be able to be selected, as they cannot receive NIM).
> Allow getting BTC address for an account when requesting a NIM address

- src/views/Checkout.vue
This PR contain 2 minor fixes:
- Added a null check for `this.$refs.disclaimer` in `mounted`hook to prevent "undefined is not an object" error.
- Fix .currency-info alignment for IOS, so that the text is not cut out and the fees are visible.
> Minor fixes for Checkout

- demos/index.html
- public/cashlink.html
- public/index.html
- src/lib/bitcoin/BitcoinJSLoader.ts
- vue.config.js
Follow up on https://github.com/nimiq/hub/pull/445.
Please check whether this builds on Mac (@Yukiioz) and Windows (@neokrept).
While changing `vue.config.js` I also added a small change for not copying `browser-warning.html.template` over to the dist folder, although not strictly related to this PR.
> Auto generate integrity hashes for core, browser warnings and BitcoinJS

- public/ServiceWorker.js
ServiceWorker.js: drop all headers from request that could trigger a HTTP 304 response
This commit contains a temporary workaround to deal with a bug in Desktop Safari
that prevents a successful resource integrity check when
a resource is loaded via the service worker
*and* the webpage forces cache revalidation (like we do).
When the resource is not modified, the server responds with a HTTP "304 -
Not modified" response. However, then Safari (supposedly) tries to check
the content from *this* response against the integrity hash *instead* of
the actual cached content. Obviously, this is pointless, since a HTTP
304 doesn't contain any content, because that would defer the entire
point, right? Hence, the integrity check won't ever succeed.. :-/
Therefore, we're now removing all headers from …
> Temporarily circumvent Desktop Safari resource integrity check bug client-side

- client/RequestBehavior.ts
- client/package.json
- client/yarn.lock
- src/i18n/en.po
When clicking on the overlay, now closing and reopening the popup for IOS instead of trying to focus it so that it doesn't look broken.
> Hub Client: add ios overlay behavior, since popup.focus() is ineffective

- src/lib/WalletStore.ts
- src/views/OnboardingSelector.vue
On iOS, especially when the Wallet is installed to homescreen, the Hub sometimes deletes its cookie, even before 7 days are over (it should not delete any data in a PWA context, but maybe because the Hub is a non-first-party domain to the PWA and opens in a webview, it is still affected?). The IndexedDB & local storage in the webview is still present then.
This deletion of the Hub cookie leads to the Wallet triggering the onboarding flow as a redirect (`disableBack: true`). This PR uses this and short-circuits the onboarding request by simply responding with a full list of accounts, which also sets the cookie (through the `_reply()` function in the `RpcApi`).
> Repopulate cookie when onboarding is called with accounts in the DB

- client/PublicRequestTypes.ts
- client/package.json
- client/yarn.lock
- package.json
- src/lib/RequestParser.ts
- src/lib/RequestTypes.ts
- src/views/RefundSwap.vue
- src/views/RefundSwapSuccess.vue
- src/views/SetupSwap.vue
- src/views/SetupSwapSuccess.vue
- yarn.lock
Includes three commits, one for each of Keyguard's native USDC PRs:
- https://github.com/nimiq/keyguard/pull/488 - uses the existing `SignPolygonTransaction` request type, no code changes necessary
- https://github.com/nimiq/keyguard/pull/490 - Update swap asset to `USDC_MATIC`, change request to use `permit` instead of `approval`, still allow bridged `USDC` to be used for swap refunds
- https://github.com/nimiq/keyguard/pull/491 - Forward required fields for resigning USDC redeem transactions via the existing `SignPolygonTransaction` flow.
> Update Hub to support new native USDC default, swaps and resigning

- deploy.sh
This PR fixes the differents deploy.sh script errors and implement the feedback from @hrxi
> Fix the deploy.sh script

- src/lib/WalletInfoCollector.ts
- src/views/LoginSuccess.vue
`f4b5904f` ("Improve syncing/detection during login") changed address scanning to strictly allow an address gap of at most `ACCOUNT_MAX_ALLOWED_ADDRESS_GAP`. Now that the more exhaustive scanning is no problem anymore with the recent performance improvements of `@nimiq/core`, we can revert this to the old implementation which is less restrictive by always checking full chunks of size `ACCOUNT_MAX_ALLOWED_ADDRESS_GAP`, which can result in address gaps between `ACCOUNT_MAX_ALLOWED_ADDRESS_GAP` and `2*ACCOUNT_MAX_ALLOWED_ADDRESS_GAP-1`. This allows to potentially find more of the user's addresses.
Reverting the commit also fixes the lint error for overlong lines, that #554 intended to fix.
The more detailed status messages in `LoginSuccess` of `f4b5904f` have not been reverted as the only …
> Revert to more exhaustive address scanning
