src/lib/RequestTypes.ts, src/router.ts, src/views/Login.vue, src/views/LoginSuccess.vue
Proper success screen is missing, but import works in general and get's returned correctly.
=> Login flow

src/views/AddAccount.vue, src/views/CheckoutErrorHandler.vue, src/views/ErrorHandler.vue, src/views/ExportFile.vue, src/views/ExportWords.vue, src/views/Login.vue, src/views/Logout.vue, src/views/SignTransaction.vue
Vue is giving me this warning when handing through to the Keyguard:
`[Vue warn]: Failed to mount component: template or render function not defined.`
I think adding empty templates doesn't hurt, what do you think?
=> Add empty templates to view components

client/yarn.lock, package.json, yarn.lock
Remove @nimiq/core devDependency and `yarn upgrade` all packages.
=> Upgrade dependencies

package.json, src/lib/RpcApi.ts, src/main.ts, src/views/ErrorHandler.vue, yarn.lock
https://sentry.io
To add more team members, we need to use a paid plan, but it has a free trial. Just tell me if I should add you.
=> Add Sentry error reporting tool

src/lib/RpcApi.ts, src/lib/StaticStore.ts, src/main.ts, src/views/ActiveAccountSelector.vue, src/views/Checkout.vue, src/views/LoginSuccess.vue, yarn.lock
=> Enable importing wallets from ActiveAccountSelector during checkout

demos/Demo.ts
- test accountsClient.list() (instead of getting the list from WalletStore)
- dynamic host (to be able to test on mobile devices)
=> demo improvements

.travis.yml, jest.config.js, package.json, yarn.lock
Thanks to @jeffesquivels for the Travis fixes!
=> Use latest @nimiq/core package

src/components/Loader.vue
The new icons need to be extracted into @nimiq/style in the future when the icon set is ready.
=> Add Loader component

src/lib/WalletStore.ts
=> Ensure IndexedDB completes writes

src/components/Loader.vue, src/views/Migrate.vue
The Loader redirect indicator is displayed at the bottom of the screen and fills clockwise in 1.5 seconds ('ease' animation):
=> Use Loader component for migrate request, add return indicator to Loader

src/components/Loader.vue
- add slots for replacement of default content
- fix status text animation for quickly changing status
- support changing the loading title
=> Loader improvements

src/lib/Constants.ts, src/lib/RequestTypes.ts, src/views/CheckoutOverview.vue
Resolves #84.
Also starts a `Constants.ts` (#86).
=> Add new optional checkout parameter 'validityDuration'

src/components/LabelInput.vue, src/lib/Constants.ts, src/lib/CookieDecoder.ts, src/lib/CookieJar.ts, src/views/LoginSuccess.vue, src/views/Rename.vue, src/views/SignupSuccess.vue
Via a custom label input component.
Resolves #80.
=> Add label length restriction

package.json, src/App.vue, src/views/Checkout.vue, src/views/CheckoutTransmission.vue, yarn.lock
This PR is based on `soeren/new-checkout` and also targeting that branch.
If I find the time, I'll add more changes to this PR.
=> Checkout style adaptions

src/lib/RpcApi.ts
Also rename state to storedState
=> Fix RpcApi.recoverState

src/views/Checkout.vue, src/views/CheckoutTransmission.vue, src/views/ChooseAddress.vue, src/views/Migrate.vue
Adds a7f7a09e9bce7f6130fe7c93e5b00bb3fbff1e4c from `soeren/merged`.
=> Remove redundant page height styles

public/blocking.css
Calculate word mark position from signet width
=> Logo position

demos/Demo.ts
Transfers last open commits from https://github.com/nimiq/accounts/issues/117.
=> Enable demos to run when deployed

src/App.vue, src/main.ts
Fixes https://github.com/nimiq/accounts/commit/9fb728b1ba00c5e55d62bef8b37fb571cc7ac529#r32924077
=> Fix service worker path and move registration to main.ts

README.md, demos/Demo.ts, src/lib/PublicRequestTypes.ts, src/lib/RequestParser.ts, src/lib/RequestTypes.ts, src/lib/RpcApi.ts, src/store.ts, src/views/SignMessage.vue, src/views/SignMessageErrorHandler.vue, src/views/SignTransaction.vue
=> Remove accountId param from signTransaction and signMessage requests

package.json, src/components/Network.vue, yarn.lock
Requires a new network client package to be released first
=> Network: pico adaptions

demos/Demo.ts, demos/index.html, package.json, tests/unit/CookieJar.spec.ts, yarn.lock
Update @nimiq/iqons for updated labelling word list + some demo wording fixes.
=> Update iqon names lib

src/lib/RpcApi.ts
Errors.InvalidRequest, Account ID not found, Address not found
=> Error reporting blacklist

src/views/SignMessage.vue, yarn.lock
Requires https://github.com/nimiq/vue-components/pull/27 to be merged first.
=> Ledger sign message

package.json, src/lib/Constants.ts, src/views/SignTransactionLedger.vue, yarn.lock
=> Correctly decode utf8 transaction data for display

src/views/OnboardingSelector.vue
According to a couple-months-old design, during checkout a headline should be displayed:
=> Display headline in onboarding menu during checkout

demos/Demo.ts, demos/index.html
Adds a global setting on the Demo page to switch between popup and redirect behavior for all requests.
=> Demo redirects

src/main.ts
=> Simplify service worker setup

src/views/SignTransactionLedger.vue, src/views/SignupLedger.vue, yarn.lock
- Use new icon components in `SignTransactionLedger` flow. This requires https://github.com/nimiq/vue-components/pull/34 to be merged first.
- Resolves https://github.com/nimiq/accounts/issues/249 introduced in https://github.com/nimiq/accounts/pull/237/files#diff-347bfea78f423a8f4d930409d2b4d442
=> Icon usage in ledger flows

src/router.ts, src/views/ErrorHandlerUnsupportedLedger.vue
Resolves https://github.com/nimiq/accounts/issues/225
=> Handle unsupported ledger requests

src/views/Checkout.vue, src/views/OnboardingSelector.vue
Onboarding while in Checkout can now return to Checkout.
=> Checkout onboarding

src/App.vue, src/lib/RpcApi.ts, src/router.ts, src/views/RequestError.vue
Also simplifies reactivity in App.vue.
=> Show error in case of client timeout in popup

client/package.json, client/yarn.lock, package.json, src/lib/RpcApi.ts, src/views/Checkout.vue, src/views/ChooseAddress.vue, src/views/SignMessage.vue, yarn.lock
in conjunction with nimiq/rpc#22
Updates @nimiq/rpc to v0.3.0 and @nimiq/keyguard-client to v0.6.0.
requires nimiq/keyguard-next#333
=> Only reject if the corresponding rpcSate has a source

src/App.vue
As an improvement over https://github.com/nimiq/accounts/pull/258
=> Use LoadingSpinner component in App.vue

src/views/SignTransactionLedger.vue, yarn.lock
Adapting to Keyguard changes made in https://github.com/nimiq/keyguard-next/pull/309.
=> Style update to reflect changes in keyguard in SignTransactionLedger

client/HubApi.ts, client/RequestBehavior.ts, client/package.json, client/yarn.lock, src/lib/PublicRequestTypes.ts, src/router.ts
Add a bunch of generics to make TypeScript derive return types and expected types for resolve from RequestType and RequestBehavior.
Resolves #252
=> Client: Derived types

client/package.json, client/tsconfig.json, client/types/index.d.ts
Turns out types were not included in the package before.
=> Actually provide types for client

src/config/config.local.ts, src/config/config.mainnet.ts, src/config/config.testnet.ts, src/lib/RpcApi.ts, src/main.ts, src/views/Migrate.vue
=> Add and use a config option reportToSentry

src/components/LedgerUi.vue, src/components/NotEnoughCookieSpace.vue, src/components/StatusScreen.vue, src/views/AddAccountSelection.vue, src/views/AddAddressLedger.vue, src/views/Checkout.vue, src/views/CheckoutTransmission.vue, src/views/ErrorHandlerUnsupportedLedger.vue, src/views/ExportSuccess.vue, src/views/LoginSuccess.vue, src/views/LogoutLedger.vue, src/views/LogoutSuccess.vue, src/views/Migrate.vue, src/views/Rename.vue, src/views/RequestError.vue, src/views/SignMessageSuccess.vue, src/views/SignTransactionLedger.vue, src/views/SignTransactionSuccess.vue, src/views/SignupLedger.vue, src/views/SignupSuccess.vue, src/views/SimpleSuccess.vue
Resolves https://github.com/nimiq/hub/issues/142
=> Rename Loader to StatusScreen

src/lib/WalletStore.ts
Also resets the database version to 1.
=> WalletStore: rename the database and accounts store

src/components/Network.vue
The second parallel request fails because the NetworkClient.Instance is already set after the first call, but internally the NetworkClient is still awaiting the RpcClient's init() call. But because the instance is already set, the Network.vue component does not wait for the second request, throwing "this._eventClient is undefined" or "Cannot read property call of undefined" errors.
This was happening in the `Migrate` request, as this request starts a balance request on mount, and if the user clicks to migrate before the network client was even connected, a parallel call to get genesisVestingContracts fails.
Fixes HUB-4B and HUB-4M in Sentry.
=> Prevent parallel calls to Network to result in the second failing

src/lib/LedgerApi.ts, yarn.lock
=> Ledger atomic requests

client/HubApi.ts, client/package.json, demos/Demo.ts, demos/index.html, package.json, src/App.vue, src/iframe.ts, src/lib/PublicRequestTypes.ts, src/lib/RequestParser.ts, src/lib/RequestTypes.ts, src/lib/RpcApi.ts, src/router.ts, src/views/CashlinkCreate.vue, src/views/CashlinkManage.vue, src/views/OnboardingSelector.vue, yarn.lock
This PR adds the creation and management UI for Cashlinks and updates the demo to include the creation of Cashlinks.
For testing please use in conjunction with the receive UI from PR #349.
=> Cashlink create manage

src/lib/CookieHelper.ts, src/lib/CookieJar.ts, src/views/LoginSuccess.vue, src/views/OnboardingSelector.vue, tests/unit/CookieJar.spec.ts
Note that I didn't test this fix.
=> Fix check for sufficient iOS cookie size on Login

src/views/ExportSuccess.vue, src/views/SignMessageSuccess.vue, src/views/SignupSuccess.vue, src/views/SimpleSuccess.vue
=> Remove slot usage for StatusScreen success titles

demos/Demo.ts, package.json, src/views/ErrorHandler.vue, src/views/LoginSuccess.vue, yarn.lock
This Pr makes use of the Error added in nimiq/keyguard#389 to implement the reset-password pseudo request.
=> Reset password error code handling

src/components/NimiqCheckoutOption.vue
=> Do not allow recipient and sender to be equal in Checkout

client/HubApi.ts, package.json, src/App.vue, src/components/CheckoutCard.vue, src/components/NimiqCheckoutCard.vue, src/components/NonNimiqCheckoutCard.vue, src/lib/RequestParser.ts, src/views/Checkout.vue, yarn.lock
A variety of checkout fixes. See commit history for details.
You can disable white space changes for easier review.
=> Checkout fixes

src/views/Checkout.vue
Do not use a session cookie anymore as most users have configured their
browsers to restore the previous session on start (tabs, session cookies, etc)
=> Checkout: expire closing of checkout disclaimer after one day

src/components/CheckoutCard.vue, src/lib/CheckoutServerApi.ts
The state request does not take a currency and is thus the same for all three currencies.
=> Simplify getState in CheckoutServerApi

client/HubApi.ts, client/package.json, src/lib/PublicRequestTypes.ts, src/lib/RequestParser.ts, src/lib/RequestTypes.ts, src/views/Checkout.vue
- Checkout disclaimer update
- Disable disclaimer for voting app
- Fix hubApi.checkout return type
As draft as the url for the voting app is potentially not final yet.
=> Some checkout adaptions

src/components/Network.vue, src/views/CashlinkManage.vue, src/views/CheckoutTransmission.vue
In case of pico -> nano consensus upgrade, the `transaction-relayed` listener on the consensus is lost, which means `Network.sendToNetwork(tx)` never resolves, showing the loading screen forever.
This PR fixes that, similar to how it was fixed in the Safe. Additionally, it adds error handling in case the transaction fails to send (with the options to reload the page or cancel the request).
@danimoh I don't know how the `SignTransactionLedger` component can support a tx-sending error, so I have not implemented that. Please have a look if we can make that possible.
**This branch is now deployed in the testnet.**
=> Fix transaction sending in case of pico->nano upgrade

demos/Demo.ts, package.json, src/components/CheckoutManualPaymentDetails.vue, src/components/NimiqCheckoutCard.vue, src/components/NonNimiqCheckoutCard.vue, src/lib/CheckoutServerApi.ts, src/lib/PublicRequestTypes.ts, src/lib/paymentOptions/BitcoinPaymentOptions.ts, src/lib/paymentOptions/EtherPaymentOptions.ts, src/lib/paymentOptions/NimiqPaymentOptions.ts, src/lib/paymentOptions/ParsedPaymentOptions.ts, src/views/Checkout.vue, src/views/SignTransactionLedger.vue, yarn.lock
Requires https://github.com/nimiq/vue-components/pull/81.
=> Add vendorMarkup option and checkout price tooltip

client/package.json, package.json, src/components/LedgerUi.vue, src/i18n/de.po, src/i18n/en.po, src/i18n/es.po, src/i18n/fr.po, src/i18n/nl.po, src/i18n/ru.po, src/i18n/uk.po, src/i18n/zh.po, src/lib/LedgerSwapProxy.ts, src/lib/MerkleTreePatch.ts, src/lib/PublicRequestTypes.ts, src/lib/RequestParser.ts, src/lib/RequestTypes.ts, src/lib/bitcoin/BitcoinLedgerUtils.ts, src/views/ActivateBitcoinLedger.vue, src/views/LoginSuccess.vue, src/views/RefundSwap.vue, src/views/RefundSwapLedger.vue, src/views/RefundSwapSuccess.vue, src/views/SetupSwap.vue, src/views/SetupSwapLedger.vue, src/views/SetupSwapSuccess.vue, src/views/SignBtcTransaction.vue, src/views/SignBtcTransactionLedger.vue, yarn.lock
This PR is for information purposes only, so the changeset is visible.
It will be merged directly, when the checks are green.
=> OASIS swaps settlement signing

demos/Demo.ts, demos/index.html, public/blocking.css, src/components/CheckoutCard.vue, src/components/CheckoutCardBitcoin.vue, src/components/CheckoutCardEthereum.vue, src/components/CheckoutCardExternal.vue, src/components/CheckoutCardNimiq.vue, src/components/CheckoutCardNimiqExternal.vue, src/components/CheckoutManualPaymentDetails.vue, src/components/NimiqCheckoutCard.vue, src/components/NonNimiqCheckoutCard.vue, src/config/config.mainnet.ts, src/i18n/de.po, src/i18n/en.po, src/i18n/es.po, src/i18n/fr.po, src/i18n/nl.po, src/i18n/ru.po, src/i18n/uk.po, src/i18n/zh.po, src/lib/PublicRequestTypes.ts, src/lib/RequestParser.ts, src/lib/RequestTypes.ts, src/lib/paymentOptions/BitcoinPaymentOptions.ts, src/lib/paymentOptions/EtherPaymentOptions.ts, src/lib/paymentOptions/NimiqPaymentOptions.ts, src/lib/paymentOptions/ParsedPaymentOptions.ts, src/views/Checkout.vue, src/views/SignTransactionLedger.vue
PR for change-set viewing purposes. Since this code is already deployed on both test- and mainnet, this PR will be merged when tests are green.
=> Nimiq Checkout Point-of-Sale improvements

src/views/ExportSuccess.vue, src/views/LoginSuccess.vue
- "Login File exported" → "Login File saved"
- "Your account is ready" → "Welcome back"
I can send you the page where the issue was created
PD: I don't have access to this repo, this is a fork
=> Updated wording

deploy.sh
see https://github.com/nimiq/hub/issues/557 for more info
=> deploy.sh: update script & implement feedback
